server:
  port: 5000

spring:
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY

  datasource:
    username: username123
    password: password123
    url: jdbc:postgresql://localhost:5432/bank_database
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      routes:
        - id: BANKSERVICE
          uri: lb://BANKSERVICE
          predicates:
            - Path=/api/v1/bank/** 
        - id: CUSTOMERSERVICE
          uri: lb://CUSTOMERSERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: ACCOUNTSERVICE
          uri: lb://ACCOUNTSERVICE
          predicates:
            - Path=/api/v1/account/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost